MOOGPS/Models/AppDbContext.cs
using Microsoft.EntityFrameworkCore;

namespace MOOGPS.Models
{
    public class AppDbContext:DbContext
    {
        public AppDbContext( DbContextOptions options):base(options)
        {

        }
        public virtual DbSet<Location> Locations { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
            modelBuilder.Entity<Location>().Property(a => a.latitude).HasColumnType("decimal").HasPrecision(18, 4);
            modelBuilder.Entity<Location>().Property(a => a.longitude).HasColumnType("decimal").HasPrecision(18, 4);
        }

    }
}

MOOGPS/Models/ErrorViewModel.cs
using System;

namespace MOOGPS.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MOOGPS/Models/Location.cs
namespace MOOGPS.Models
{
    public class Location
    {

        public int Id { get; set; }
        public decimal latitude { get; set; }
        public decimal longitude { get; set; }
    }
}

MOOGPS/Controllers/GPSController.cs
using MOOGPS.Interfaces;
using MOOGPS.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;

namespace MOOGPS.Controllers
{
    public class GPSController : Controller
    {
        private readonly AppDbContext _context;
        private readonly ILOcation _gPS;

        public GPSController(AppDbContext context, ILOcation gPS)
        {
            _context = context;
            _gPS = gPS;
        }
        public IActionResult Index()
        {
            return View(_gPS.GetLocations());
        }

        public IActionResult Create()
        {
            var gps = new Location();
            return View(gps);
        }
        [HttpPost]
        public IActionResult Create(Location gps)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _gPS.CreateLocation(gps);
                    
                   return RedirectToAction(nameof(Index));
                }
                else
                    return View();

            }
            catch (Exception ex)
            {
                return View();


            }

        }

    }
}

MOOGPS/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MOOGPS.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MOOGPS.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MOOGPS/Views/GPS/Create.cshtml
@model MOOGPS.Models.Location

<style>
    #mapCanvas {
        width: 750px;
        height: 400px;
        float: right;
    }
  
  
</style>
@{
    ViewData["Title"] = "Create";
}
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD_N1k4WKCdiZqCIjjgO0aaKz1Y19JqYqw"></script>
<h1>Create - GPS </h1>

<div class="row">
   
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
             <div class="form-group">
         <div class="row">
        
           <div class="col-sm-9 col-xs-12">
               <div id="mapCanvas"></div>
           </div>
           <div class="col-sm-2 col-xs-12 "  style="margin:10px;">
               <b>Marker status</b>
               <div id="markerStatus"><i>Map_Clickanddragthemarker.</i></div>
            
           </div>
       </div>
       </div>
            <div class="form-group">
                <label asp-for="latitude" class="control-label" ></label>
                <input asp-for="latitude" class="form-control" />
                <span asp-validation-for="latitude" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="longitude" class="control-label"></label>
                <input asp-for="longitude" class="form-control"  />
                <span asp-validation-for="longitude" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>


<div>
    <a asp-action="Index">Back to List</a>
</div>
<script>
      var geocoder = new google.maps.Geocoder();

     // Onload handler to fire off the app.
    google.maps.event.addDomListener(window, 'load', initialize);
     // Block Of Map---------------------------------------
  
    var latLng = new google.maps.LatLng(26.893, 29.57);
    var zoom = 4;
    function geocodePosition(pos) {
        geocoder.geocode({
            latLng: pos
        }, function (responses) {
            
        });
    }

    function  updateMarkerStatus(str) {
        document.getElementById('markerStatus').innerHTML = str;
    }

    function  updateMarkerPosition(latLng) {
        $("#latitude").val(latLng.lat());
        $("#longitude").val(latLng.lng());
    }

    function initialize() {
        var map = new google.maps.Map(document.getElementById('mapCanvas'), {
            zoom: zoom,
            center: latLng,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        });
        var marker = new google.maps.Marker({
            position: latLng,
            title: 'Point A',
            map: map,
            draggable: true
        });

        // Update current position info.
         updateMarkerPosition(latLng);
        geocodePosition(latLng);

        // Add dragging event listeners.
        google.maps.event.addListener(marker, 'dragstart', function () {
            
        });

        google.maps.event.addListener(marker, 'drag', function () {
             updateMarkerStatus('Dragging...');
             updateMarkerPosition(marker.getPosition());
        });

        google.maps.event.addListener(marker, 'dragend', function () {
             updateMarkerStatus('Drag ended');
            geocodePosition(marker.getPosition());
        });
    }

   

</script>
@section Scripts {
    @{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
}

MOOGPS/Views/GPS/Index.cshtml
@model IEnumerable<MOOGPS.Models.Location>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a  class="btn btn-primary" asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.latitude)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.longitude)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.latitude)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.longitude)
            </td>
            <td>
                <button type="button" class="btn btn-info" onclick="ViewLocation(@item.latitude,@item.longitude)"> INFO</button>
              
            </td>
        </tr>
}
    </tbody>
</table>

<script>
     function ViewLocation(latitudeG, longitudeG) {
        window.open('http://www.google.com/maps/place/' + latitudeG + ',' + longitudeG);
        $(".widget-reveal-card-open").show();
    }
</script>

MOOGPS/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MOOGPS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MOOGPS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MOOGPS</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="GPS" asp-action="Index">GPS</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MOOGPS - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>